apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "herald.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "herald.labels" . | nindent 4 }}
data:
  herald.json: |
    {{- .Values.config | toPrettyJson | nindent 4 }}
