{{- if .Values.cache.persistent }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "herald.fullname" . }}-cache
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "herald.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.cache.storageClass }}
  storageClassName: {{ .Values.cache.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.cache.size }}
{{- end }}
